name: offline_engine
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^3.0.0
  flutter_riverpod: ^3.3.2
  freezed_annotation: ^3.1.0
  build_runner: ^2.15.0
  dio: ^5.4.0
  dartz: ^0.10.1
  riverpod_annotation: ^4.0.2
  drift: ^2.34.0
  uuid: ^4.5.3
  path_provider: ^2.1.5
  path: ^1.9.1
  json_annotation: ^4.12.0
  get_it: ^9.2.1
  fluttertoast: ^9.1.0

  j_client:
    path: ../dio_client
  shared_preferences: ^2.5.5
  internet_connection_checker_plus: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^3.0.0
  json_serializable: ^6.11.1
  drift_dev: ^2.34.0
  freezed: ^3.2.5
  riverpod_generator: ^4.0.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/offline_engine_logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
